tokenizer:
  vocabulary:
    delimiter: "\t"
    file: "/home/dallmann/uni/research/dota/datasets/small/preprocessed/splits/items.vocab"
  special_tokens:
    pad_token: "<PAD>"
model:
  num_items: 248
  item_embedding_dim: 32
  hidden_size: 128
  num_layers: 1
  dropout: 0.25
module:
  learning_rate: 0.001
  beta_1: 0.99
  beta_2: 0.998
  metrics:
    recall:
      - 1
      - 3
      - 5
      - 10
    mrr:
      - 1
      - 3
      - 5
      - 10
datasets:
  train:
    dataset:
      csv_file: "/home/dallmann/uni/research/dota/datasets/small/preprocessed/splits/train.csv"
      csv_file_index: "/home/dallmann/uni/research/dota/datasets/small/preprocessed/splits/train.csv.idx"
      nip_index_file: "/home/dallmann/uni/research/dota/datasets/small/preprocessed/splits/train.csv.nip"
      parser:
        delimiter: "\t"
        item_column_name: "item_id"
    loader:
      batch_size: 512
      max_seq_length: 100
  validation:
    dataset:
      csv_file: "/home/dallmann/uni/research/dota/datasets/small/preprocessed/splits/valid.csv"
      csv_file_index: "/home/dallmann/uni/research/dota/datasets/small/preprocessed/splits/valid.csv.idx"
      nip_index_file: "/home/dallmann/uni/research/dota/datasets/small/preprocessed/splits/valid.csv.nip"
      parser:
        delimiter: "\t"
        item_column_name: "item_id"
    loader:
      batch_size: 512
      max_seq_length: 100
  test:
    dataset:
      csv_file: "/home/dallmann/uni/research/dota/datasets/small/preprocessed/splits/test.csv"
      csv_file_index: "/home/dallmann/uni/research/dota/datasets/small/preprocessed/splits/test.csv.idx"
      nip_index_file: "/home/dallmann/uni/research/dota/datasets/small/preprocessed/splits/test.csv.nip"
      parser:
        delimiter: "\t"
        item_column_name: "item_id"
    loader:
      batch_size: 512
      max_seq_length: 100
trainer:
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  default_root_dir: /tmp/checkpoints
  checkpoint:
    filepath: "/tmp/checkpoints/{epoch}-{recall_at_5:.4f}"
    save_top_k: 3
    monitor: "val_loss"
  gpus: 1




