tokenizer:
  vocabulary:
    delimiter: "\t"
    file: "/home/dallmann/uni/research/dota/datasets/small/preprocessed/splits/items.vocab"
  special_tokens:
    pad_token: "<PAD>"
model:
  transformer_hidden_size: 64
  num_transformer_heads: 4
  num_transformer_layers: 3
  item_vocab_size: 248
  max_seq_length: 100
  dropout: 0.1
module:
  learning_rate: 0.001
  beta_1: 0.99
  beta_2: 0.998
  batch_first: true
  metrics:
    recall:
      - 1
      - 3
      - 5
      - 10
    mrr:
      - 1
      - 3
      - 5
      - 10
datasets:
  train:
    dataset:
      csv_file: "/home/dallmann/uni/research/dota/datasets/small/preprocessed/splits/train.csv"
      csv_file_index: "/home/dallmann/uni/research/dota/datasets/small/preprocessed/splits/train.csv.idx"
      delimiter: "\t"
      item_column_name: "item_id"
    loader:
      batch_size: 128
      max_seq_length: 100
  validation:
    dataset:
      csv_file: "/home/dallmann/uni/research/dota/datasets/small/preprocessed/splits/valid.csv"
      csv_file_index: "/home/dallmann/uni/research/dota/datasets/small/preprocessed/splits/valid.csv.idx"
      nip_index_file: "/home/dallmann/uni/research/dota/datasets/small/preprocessed/splits/valid.csv.nip"
      delimiter: "\t"
      item_column_name: "item_id"
    loader:
      batch_size: 128
      max_seq_length: 100
  test:
    dataset:
      csv_file: "/home/dallmann/uni/research/dota/datasets/small/preprocessed/splits/test.csv"
      csv_file_index: "/home/dallmann/uni/research/dota/datasets/small/preprocessed/splits/test.csv.idx"
      nip_index_file: "/home/dallmann/uni/research/dota/datasets/small/preprocessed/splits/test.csv.nip"
      delimiter: "\t"
      item_column_name: "item_id"
    loader:
      batch_size: 128
      max_seq_length: 100
trainer:
  default_root_dir: /tmp/checkpoints
  checkpoint:
    filepath: "/tmp/checkpoints/{epoch}-{recall_at_5:.4f}"
    save_top_k: 3
    monitor: "recall_at_5"
  gpus: 1