parser: &parser
  item_column_name: title
loader: &loader
  batch_size: 64
  max_seq_length: 200
  num_workers: 4
  pad_direction: left
datasets:
  test:
    dataset:
      csv_file: /scratch/jane-doe-framework/datasets/ml-20m/ml-20m.csv
      csv_file_index: /scratch/jane-doe-framework/datasets/ml-20m/ml-20m.idx
      parser: *parser
      nip_index_file: /scratch/jane-doe-framework/datasets/ml-20m/test.loo.idx
    loader: *loader
  train:
    dataset:
      csv_file: /scratch/jane-doe-framework/datasets/ml-20m/ml-20m.csv
      csv_file_index: /scratch/jane-doe-framework/datasets/ml-20m/ml-20m.idx
      truncated_seq_index_file: /scratch/jane-doe-framework/datasets/ml-20m/valid.loo.idx
      parser: *parser
    loader: *loader
  validation:
    dataset:
      csv_file: /scratch/jane-doe-framework/datasets/ml-20m/ml-20m.csv
      csv_file_index: /scratch/jane-doe-framework/datasets/ml-20m/ml-20m.idx
      nip_index_file: /scratch/jane-doe-framework/datasets/ml-20m/valid.loo.idx
      parser: *parser
    loader: *loader
model:
  item_vocab_size: 27265
  max_seq_length: 200
  num_transformer_heads: 2
  num_transformer_layers: 2
  transformer_hidden_size: 64
  transformer_dropout: 0.2
module:
  batch_first: false
  mask_probability: 0.2
  beta_1: 0.99
  beta_2: 0.998
  learning_rate: 0.0001
  weight_decay: 0.00
  num_warmup_steps: 3
  pad_direction: left
  sampled_metrics:
    sample_probability_file: /scratch/jane-doe-framework/datasets/ml-20m/popularity.txt
    num_negative_samples: 100
    metrics:
      recall:
        - 1
        - 5
        - 10
tokenizer:
  special_tokens:
    pad_token: <PAD>
    mask_token: <MASK>
    unk_token: <UNK>
  vocabulary:
    delimiter: "\t"
    file: /scratch/jane-doe-framework/datasets/ml-20m/vocab_title.txt
trainer:
  checkpoints:
    monitor: recall_at_5
    save_top_k: 3
  gradient_clip_val: 0
  default_root_dir: /scratch/jane-doe-framework/experiments/ml-20m/bert4rec
  gpus: 1
