parser: &parser
  item_column_name: title
loader: &loader
  batch_size: 16
  max_seq_length: 50
datasets:
  test:
    dataset:
      csv_file: ../dataset/dataset/ml-1m_3_5_5/ml-1m.csv
      csv_file_index: ../dataset/dataset/ml-1m_3_5_5/ml-1m.idx
      parser: *parser
      nip_index_file: ../dataset/dataset/ml-1m_3_5_5/test.loo.idx
    loader: *loader
  train:
    dataset:
      csv_file: ../dataset/dataset/ml-1m_3_5_5/ml-1m.csv
      csv_file_index: ../dataset/dataset/ml-1m_3_5_5/ml-1m.idx
      nip_index_file: ../dataset/dataset/ml-1m_3_5_5/train.nip.idx
      parser: *parser
    loader: *loader
  validation:
    dataset:
      csv_file: ../dataset/dataset/ml-1m_3_5_5/ml-1m.csv
      csv_file_index: ../dataset/dataset/ml-1m_3_5_5/ml-1m.idx
      nip_index_file: ../dataset/dataset/ml-1m_3_5_5/valid.loo.idx
      parser: *parser
    loader: *loader
model:
  item_vocab_size: 3419
  cell_type: gru
  item_embedding_dim: 64
  hidden_size: 64
  num_layers: 2
  dropout: 0.2
module:
  metrics:
    mrr:
      - 1
      - 3
      - 5
    recall:
      - 1
      - 5
      - 10
  sampled_metrics:
    sample_probability_file: ../dataset/dataset/ml-1m_3_5_5/popularity.txt
    num_negative_samples: 100
    metrics:
      recall:
        - 1
        - 5
        - 10
tokenizer:
  special_tokens:
    pad_token: <PAD>
    mask_token: <MASK>
    unk_token: <UNK>
  vocabulary:
    delimiter: "\t"
    file: ../dataset/dataset/ml-1m_3_5_5/vocab_title.txt
trainer:
  checkpoints:
    monitor: recall_at_5
    save_top_k: 3
  max_epochs: 100
  default_root_dir: ../dataset/dataset/experiments/ml-1m/gru