parser: &parser
  item_column_name: title
loader: &loader
  batch_size: 64
  max_seq_length: 200
  num_workers: 4
datasets:
  test:
    dataset:
      csv_file: /ssd/ml-20m/ml-20m.csv
      csv_file_index: /ssd/ml-20m/ml-20m.idx
      parser: *parser
      nip_index_file: /ssd/ml-20m/ml-1m.test.loo.idx
    loader: *loader
  train:
    dataset:
      csv_file: /ssd/ml-20m/ml-20m.csv
      csv_file_index: /ssd/ml-20m/ml-20m.idx
      # FIXME this is the wrong index for validation only
      nip_index_file: /ssd/ml-20m/ml-1m.validation.loo.idx
      parser: *parser
    loader: *loader
  validation:
    dataset:
      csv_file: /ssd/ml-20m/ml-20m.csv
      csv_file_index: /ssd/ml-20m/ml-20m.idx
      nip_index_file: /ssd/ml-20m/ml-1m.validation.loo.idx
      parser: *parser
    loader: *loader
model:
  item_vocab_size: 26732
  cell_type: gru
  item_embedding_dim:
    hyper_opt:
      suggest: int
      params:
        low: 2
        high: 256
        step: 2
  hidden_size:
    hyper_opt:
      suggest: int
      params:
        low: 2
        high: 256
        step: 2
  num_layers:
    hyper_opt:
      suggest: int
      params:
        low: 2
        high: 6
        step: 1
  bidirectional:
    hyper_opt:
      suggest: suggest
      params:
        choices: [True, False]
  dropout:
    hyper_opt:
      suggest: float
      params:
        low: 0.0
        high: 0.9
        step: 0.1
  nonlinearity: relu
module:
  beta_1: 0.99
  beta_2: 0.998
  learning_rate: 0.0001
  weight_decay: 0.00
  sampled_metrics:
    sample_probability_file: /ssd/ml-20m/popularity.txt
    num_negative_samples: 100
    metrics:
      recall:
        - 1
        - 5
        - 10
tokenizer:
  special_tokens:
    pad_token: <PAD>
    mask_token: <MASK>
    unk_token: <UNK>
  vocabulary:
    delimiter: "\t"
    file: /ssd/ml-20m/vocab_title.txt
trainer:
  checkpoint:
    monitor: recall_at_10/sampled
    save_top_k: 3
    mode: max
  gradient_clip_val: 0.0
  default_root_dir: /scratch/jane-doe-framework/experiments/ml-20m/gru-hp
  gpus: 1
  max_epochs: 20
  logger:
    type: mlflow
    experiment_name: gru-hp
    tracking_uri: http://mlflow-service:5000
