parser: &parser
  item_column_name: item_id
loader: &loader
  batch_size: 2
  max_seq_length: 5
datasets:
  test:
    dataset:
      csv_file: ../tests/example_dataset/train.csv
      csv_file_index: ../tests/example_dataset/train.idx
      nip_index_file: ../tests/example_dataset/train.nip.idx
      parser: *parser
    loader: *loader
  train:
    dataset:
      csv_file: ../tests/example_dataset/train.csv
      csv_file_index: ../tests/example_dataset/train.idx
      parser: *parser
    loader: *loader
  validation:
    dataset:
      csv_file: ../tests/example_dataset/train.csv
      csv_file_index: ../tests/example_dataset/train.idx
      nip_index_file: ../tests/example_dataset/train.nip.idx
      parser: *parser
    loader: *loader
model:
  dropout: 0.1
  item_vocab_size: 13
  user_vocab_size: 0
  max_seq_length: 5
  embedding_size: 4
  num_vertical_filters: 2
  num_horizontal_filters: 1
  fc_activation_fn: relu
  conv_activation_fn: relu
module:
  learning_rate: 0.001
  weight_decay: 0.01
  metrics:
    mrr:
      - 1
      - 3
      - 5
    recall:
      - 1
      - 3
      - 5
tokenizer:
  special_tokens:
    pad_token: <PAD>
    mask_token: <MASK>
    unk_token: <UNK>
  vocabulary:
    delimiter: "\t"
    file: ../tests/example_dataset/vocab.txt
trainer:
  checkpoint:
    monitor: recall@5
    save_top_k: 3
