datasets:
  test:
    dataset:
      csv_file: /Users/nosebrain/Desktop/small/test.csv
      csv_file_index: /Users/nosebrain/Desktop/small/test.idx
      parser:
        delimiter: "\t"
        item_column_name: item_id
 #       item_separator: ' + '
      nip_index_file: /Users/nosebrain/Desktop/small/test.nip.idx
    loader:
      batch_size: 4
      max_seq_length: 10
#      max_seq_step_length: 5
  train:
    dataset:
      csv_file: /Users/nosebrain/Desktop/small/train.csv
      csv_file_index: /Users/nosebrain/Desktop/small/train.idx
      parser:
        delimiter: "\t"
        item_column_name: item_id
#        item_separator: ' + '
    loader:
      batch_size: 4
      max_seq_length: 10
 #     max_seq_step_length: 5
  validation:
    dataset:
      csv_file: /Users/nosebrain/Desktop/small/valid.csv
      csv_file_index: /Users/nosebrain/Desktop/small/valid.idx
      parser:
        delimiter: "\t"
        item_column_name: item_id
  #      item_separator: ' + '
      nip_index_file: /Users/nosebrain/Desktop/small/valid.nip.idx
    loader:
      batch_size: 4
      max_seq_length: 10
  #    max_seq_step_length: 5
model:
  dropout: 0.1
  item_vocab_size: 250
  user_vocab_size: 0
  max_seq_length: 10
  embedding_size: 16
  num_vertical_filters: 5
  num_horizontal_filters: 2
  fc_activation_fn: relu
  conv_activation_fn: relu
  #embedding_mode: mean
module:
  learning_rate: 0.001
  weight_decay: 0.01
  metrics:
    recall:
      - 1
      - 3
      - 5
      - 10
    precision:
      - 1
      - 3
      - 5
      - 10
tokenizer:
  special_tokens:
    pad_token: <PAD>
    unk_token: <UNK>
  vocabulary:
    delimiter: "\t"
    file: /Users/nosebrain/Desktop/small/items.vocab
trainer:
  checkpoints:
    monitor: recall_at_5
    save_top_k: 3
  default_root_dir: /tmp/checkpoints
  limit_train_batches: 10
  limit_val_batches: 10
