apiVersion: v1
kind: Pod
metadata:
  name: mlflow-server
  labels:
    app: mlflow-service
spec:
  containers:
    - name: mlflow
      image: gitlab2.informatik.uni-wuerzburg.de:4567/dmir/dallmann/recommender/mlflow:latest
      imagePullPolicy: "Always"
      resources:
        requests: &resources
          cpu: "1"
          memory: "2Gi"
        limits: *resources
      command:
        - "mlflow"
        - "server"
        - "-h 0.0.0.0"
        - "--backend-store-uri=file:///data"
      volumeMounts:
        - mountPath: /data
          name: home
      ports:
        - containerPort: 5000
  imagePullSecrets:
    - name: gitlab-registry
  restartPolicy: "Never"
  volumes:
    - name: home
      cephfs:
        monitors:
          - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
        user: studbonda
        path: "/home/stud/bonda/model_logging/mlflow"
        secretRef:
          name: ceph-secret
