datamodule:
  data_sources:
    batch_size: 64
    file_prefix: ml-20m
    mask_probability: 0.2
    mask_seed: 42
    max_seq_length: 200
    num_workers: 16
    split: ratio_split
    test:
      processors:
      - type: target_extractor
      - type: last_item_mask
      type: session
    train:
      processors:
      - exclude_features:
        - item_id_type
        mask_probability: 0.2
        only_last_item_mask_prob: 0.1
        type: cloze
      type: session
    validation:
      processors:
      - type: target_extractor
      - type: last_item_mask
      type: session
  dataset: ml-20m
  preprocessing:
    create_loo: false
    create_lpo: false
    extraction_directory: /ssd/dataset/download #/home/ls6/fischer/datasets/plp-paper/ml-20m/download
    output_directory: /ssd/dataset/processed
evaluation:
  evaluators:
  - type: sid
    use_session_id: false
  - type: recommendation
  - type: metrics
  - type: input
  - type: scores
  - type: target
  number_predictions: 5
  writer:
    type: csv-single-line
features:
  genres:
    column_name: genres
    delimiter: '|'
    element_type: str
    max_sequence_step_length: 3
    sequence_length: 200
    tokenizer:
      special_tokens:
        mask_token: <MASK>
        pad_token: <PAD>
        unk_token: <UNK>
      vocabulary:
        file: ml-20m.vocabulary.genres-split.txt
    type: list
  item:
    column_name: title
    sequence_length: 200
    tokenizer:
      special_tokens:
        mask_token: <MASK>
        pad_token: <PAD>
        unk_token: <UNK>
      vocabulary: null
module:
  metrics:
    fixed:
      item_file: /home/ls6/fischer/datasets/plp-paper/ml-20m/processed/ratio_split-0.8_0.1_0.1/ml-20m.vocabulary.title.txt
      metrics:
        mrr:
        - 1
        - 5
        - 10
        ndcg:
        - 1
        - 5
        - 10
        recall:
        - 1
        - 5
        - 10
      model_vocabulary: /home/ls6/fischer/datasets/plp-paper/ml-20m/processed/ratio_split-0.8_0.1_0.1/ml-20m.vocabulary.title.txt
    full:
      metrics:
        mrr:
        - 1
        - 5
        - 10
        ndcg:
        - 1
        - 5
        - 10
        recall:
        - 1
        - 5
        - 10
  model:
    max_seq_length: 200
    num_transformer_heads: 2
    num_transformer_layers: 2
    transformer_dropout: 0.2
    transformer_hidden_size: 64
  type: content-bert4rec
templates:
  unified_output:
    path: /home/ls6/fischer/plp-paper/experiments/ml-20m/bert4rec/100-base-token-study
trainer:
  check_val_every_n_epoch: 5
  checkpoint:
    mode: max
    monitor: recall@10
    save_top_k: 3
  deterministic: true
  early_stopping:
    min_delta: 0.001
    mode: max
    monitor: recall@10
    patience: 100
  gpus: 1
  loggers:
    aim:
      experiment: ml-20m-bert4rec-100-base-token-study
      repo: /home/ls6/fischer/model_logging/aim/
    #csv:
     # save_dir: /home/ls6/fischer/plp-paper/experiments/ml-20m/bert4rec/100-base-token-study
    #mlflow:
    #  experiment_name: ml-20m-bert4rec-100-base-token-study
    #  tracking_uri: file:/home/ls6/fischer/model_logging/mlflow/
  max_epochs: 100
