parser: &parser
  item_column_name: title
  additional_features:
    userId:
      type: int
      sequence: false
loader: &loader
  batch_size: 4
  max_seq_length: 200
datasets:
  test:
    dataset:
      csv_file: ../dataset/dataset/ml-20m_3_5_5/ml-20m.csv
      csv_file_index: ../dataset/dataset/ml-20m_3_5_5/ml-20m.idx
      nip_index_file: ../dataset/dataset/ml-20m_3_5_5/test.loo.idx
      parser: *parser
    loader: *loader
  train:
    dataset:
      csv_file: ../dataset/dataset/ml-20m_3_5_5/ml-20m.csv
      csv_file_index: ../dataset/dataset/ml-20m_3_5_5/ml-20m.idx
      nip_index_file: ../dataset/dataset/ml-20m_3_5_5/valid.loo.idx
      parser: *parser
    loader: *loader
  validation:
    dataset:
      csv_file: ../dataset/dataset/ml-20m_3_5_5/ml-20m.csv
      csv_file_index: ../dataset/dataset/ml-20m_3_5_5/ml-20m.idx
      nip_index_file: ../dataset/dataset/ml-20m_3_5_5/valid.loo.idx
      parser: *parser
    loader: *loader
module:
    item_vocab_size: 18339
    metrics:
        recall:
          - 1
          - 5
          - 10
tokenizer:
  special_tokens:
    pad_token: <PAD>
    mask_token: <MASK>
    unk_token: <UNK>
  vocabulary:
    delimiter: "\t"
    file: ../dataset/dataset/ml-20m_3_5_5/vocab_title.txt
trainer:
  limit_train_batches: 1000
  limit_val_batches: 100
  max_epochs: 1
  checkpoint:
    monitor: recall_at_10
    save_top_k: 3
  gradient_clip_val: 5
  default_root_dir: ../dataset/experiments/ml-20m/pop
