parser: &parser
  item_column_name: title
loader: &loader
  batch_size: 64
  max_seq_length: 200
  num_workers: 4
datasets:
  test:
    dataset:
      csv_file: /ssd/ml-20m/ml-20m.csv
      csv_file_index: /ssd/ml-20m/ml-20m.idx
      parser: *parser
      nip_index_file: /ssd/ml-20m/test.loo.idx
    loader: *loader
  train:
    dataset:
      csv_file: /ssd/ml-20m/ml-20m.csv
      csv_file_index: /ssd/ml-20m/ml-20m.idx
      truncated_seq_index_file: /ssd/ml-20m/valid.loo.idx
      parser: *parser
    loader: *loader
  validation:
    dataset:
      csv_file: /ssd/ml-20m/ml-20m.csv
      csv_file_index: /ssd/ml-20m/ml-20m.idx
      nip_index_file: /ssd/ml-20m/valid.loo.idx
      parser: *parser
    loader: *loader
model:
  cell_type:
    optuna:
      suggest_categorical: {name: cell_type, choices: ["gru", "lstm", "rnn"] }
  item_embedding_size:
    optuna:
      suggest_int: {name: item_embedding_size, low: 2, high: 256, step: 2}
  hidden_size:
    optuna:
      suggest_int: {name: hidden_size, low: 2, high: 256, step: 2}
  num_layers:
    optuna:
      suggest_int: {name: num_layers, low: 2, high: 6, step: 1}
  bidirectional:
    optuna:
      suggest_categorical: {name: bidirectional, choices: [True, False] }
  dropout:
    optuna:
      suggest_float: {name: dropout, low: 0.0, high: 0.9, step: 0.1}
  nonlinearity:
    optuna:
      suggest_categorical: {name: nonlinearity, choices: ["relu", "tanh"] }
      conditional: celltype == 'rnn'
module:
  beta_1: 0.99
  beta_2: 0.998
  learning_rate: 0.0001
  weight_decay: 0.00
  sampled_metrics:
    sample_probability_file: /ssd/ml-20m/popularity.txt
    num_negative_samples: 100
    metrics:
      recall:
        - 1
        - 5
        - 10
tokenizer:
  special_tokens:
    pad_token: <PAD>
    mask_token: <MASK>
    unk_token: <UNK>
  vocabulary:
    delimiter: "\t"
    file: /ssd/ml-20m/vocab_title.txt
trainer:
  checkpoint:
    monitor: recall_at_10/sampled
    save_top_k: 3
    mode: max
  gradient_clip_val: 0.0
  default_root_dir: /scratch/jane-doe-framework/experiments/ml-20m/bert4rec
  gpus: 1
  max_epochs: 800