datasets:
  test:
    dataset:
      csv_file: /Users/nosebrain/Desktop/small/test.csv
      csv_file_index: /Users/nosebrain/Desktop/small/test.idx
      parser:
        delimiter: "\t"
        item_column_name: item_id
      nip_index_file: /Users/nosebrain/Desktop/small/test.nip.idx
    loader:
      num_workers: 0
      batch_size: 4
      max_seq_length: 50
  train:
    dataset:
      csv_file: /Users/nosebrain/Desktop/small/train.csv
      csv_file_index: /Users/nosebrain/Desktop/small/train.idx
      parser:
        delimiter: "\t"
        item_column_name: item_id
    loader:
      num_workers: 0
      batch_size: 4
      max_seq_length: 50
  validation:
    dataset:
      csv_file: /Users/nosebrain/Desktop/small/valid.csv
      csv_file_index: /Users/nosebrain/Desktop/small/valid.idx
      parser:
        delimiter: "\t"
        item_column_name: item_id
      nip_index_file: /Users/nosebrain/Desktop/small/valid.nip.idx
    loader:
      num_workers: 0
      batch_size: 4
      max_seq_length: 50
model:
  item_vocab_size: 250
  max_seq_length: 50
  num_transformer_heads: 2
  num_transformer_layers: 2
  transformer_hidden_size: 128
  transformer_dropout: 0.1
module:
  batch_first: true
  mask_probability: 0.15
  beta_1: 0.99
  beta_2: 0.998
  learning_rate: 0.001
  weight_decay: 0.01
  num_warmup_steps: 3
  metrics:
    precision:
      - 1
      - 3
      - 5
    recall:
      - 1
      - 3
      - 5
    f1:
      - 1
      - 3
      - 5
tokenizer:
  special_tokens:
    pad_token: <PAD>
    mask_token: <MASK>
    unk_token: <UNK>
  vocabulary:
    delimiter: "\t"
    file: /Users/nosebrain/Desktop/small/items.vocab
trainer:
  logger:
    type: mlflow
    tracking_uri: file:/tmp/mlflow
  limit_val_batches: 10
  checkpoints:
    monitor: f1_at_5
    save_top_k: 3
  max_epochs: 1
