datasets:
  test:
    dataset:
      csv_file: /Users/nosebrain/Desktop/small/test.csv
      csv_file_index: /Users/nosebrain/Desktop/small/test.idx
      parser:
        delimiter: "\t"
        item_column_name: item_id
        item_separator: ' + '
      nip_index_file: /Users/nosebrain/Desktop/small/test.nip.idx
    loader:
      batch_size: 4
      max_seq_length: 10
      max_seq_step_length: 5
  train:
    dataset:
      csv_file: /Users/nosebrain/Desktop/small/train.csv
      csv_file_index: /Users/nosebrain/Desktop/small/train.idx
      nip_index_file: /Users/nosebrain/Desktop/small/train.nip.idx
      parser:
        delimiter: "\t"
        item_column_name: item_id
        item_separator: ' + '
    loader:
      batch_size: 4
      max_seq_length: 10
      max_seq_step_length: 5
  validation:
    dataset:
      csv_file: /Users/nosebrain/Desktop/small/valid.csv
      csv_file_index: /Users/nosebrain/Desktop/small/valid.idx
      parser:
        delimiter: "\t"
        item_column_name: item_id
        item_separator: ' + '
      nip_index_file: /Users/nosebrain/Desktop/small/valid.nip.idx
    loader:
      batch_size: 4
      max_seq_length: 10
      max_seq_step_length: 5
model:
  num_items: 250
  item_embedding_dim: 32
  hidden_size: 128
  num_layers: 1
  dropout: 0.1
  embedding_mode: mean
module:
  beta_1: 0.99
  beta_2: 0.998
  learning_rate: 0.001
  metrics:
    precision:
      - 1
      - 3
      - 5
    recall:
      - 1
      - 3
      - 5
    f1:
      - 1
      - 3
      - 5
tokenizer:
  special_tokens:
    pad_token: <PAD>
    mask_token: <MASK>
    unk_token: <UNK>
  vocabulary:
    delimiter: "\t"
    file: /Users/nosebrain/Desktop/small/items.vocab
trainer:
  limit_train_batches: 10
  limit_val_batches: 10
  checkpoints:
    monitor: recall_at_5
    save_top_k: 3
  max_epochs: 1
