datamodule:
  data_sources:
    batch_size: 64
    file_prefix: ml-20m-extended
    mask_probability: 0.2
    mask_seed: 42
    max_seq_length: 200
    num_workers: 16
    split: ratio_split
    test:
      processors:
      - type: target_extractor
      type: session
    train:
      processors:
      - parallel: true
        type: target_extractor
      type: session
    validation:
      processors:
      - type: target_extractor
      type: session
  dataset: ml-20m-extended
  preprocessing:
    extraction_directory: /ssd/dataset
    output_directory: /ssd/dataset
evaluation:
  evaluators:
  - type: sid
    use_session_id: false
  - type: recommendation
  - type: metrics
  - type: input
  - type: scores
  - type: target
  number_predictions: 5
  writer:
    type: csv-single-line
features:
  genres:
    column_name: genres
    delimiter: '|'
    element_type: str
    max_sequence_step_length: 3
    sequence_length: 200
    tokenizer:
      special_tokens:
        mask_token: <MASK>
        pad_token: <PAD>
        unk_token: <UNK>
      vocabulary:
        file: ml-20m-extended.vocabulary.genres-split.txt
    type: list
  item:
    column_name: title
    sequence_length: 200
    tokenizer:
      special_tokens:
        mask_token: <MASK>
        pad_token: <PAD>
        unk_token: <UNK>
      vocabulary: null
  item_id_type:
    column_name: item_id_type
    run_tokenization: false
    sequence_length: 200
    special_values:
      mask_value: '0'
      pad_value: '0'
      unk_value: '0'
    type: int
  title_genres:
    column_name: title_genres
    sequence_length: 200
    tokenizer:
      special_tokens:
        mask_token: <MASK>
        pad_token: <PAD>
        unk_token: <UNK>
      vocabulary: null
  title_uid:
    column_name: title_uid
    sequence_length: 200
    tokenizer:
      special_tokens:
        mask_token: <MASK>
        pad_token: <PAD>
        unk_token: <UNK>
      vocabulary: null
module:
  metrics:
    fixed:
      item_file: /home/ls6/fischer/datasets/plp-paper/ml-20m/processed/ratio_split-0.8_0.1_0.1/ml-20m.vocabulary.title.txt
      metrics:
        mrr:
        - 1
        - 5
        - 10
        ndcg:
        - 1
        - 5
        - 10
        recall:
        - 1
        - 5
        - 10
    full:
      metrics:
        mrr:
        - 1
        - 5
        - 10
        ndcg:
        - 1
        - 5
        - 10
        recall:
        - 1
        - 5
        - 10
  model:
    item_id_type_settings:
       name: "item_id_type"
       extra_embbedding: false
    item_attributes:
      prefusion:
        genres:
          embedding: keys
          embedding_type: linear_upscale
          merge_function: add
          plp_only: True
    max_seq_length: 200
    num_transformer_heads: 2
    num_transformer_layers: 2
    transformer_dropout: 0.2
    transformer_hidden_size: 64
  type: content-sasrec-full
templates:
  unified_output:
    path: /home/ls6/fischer/plp-paper/experiments/ml-20m-extended/sasrec/100-plp-base-token-genres-nia
trainer:
  check_val_every_n_epoch: 5
  checkpoint:
    mode: max
    monitor: recall@10
    save_top_k: 3
  #deterministic: true
  early_stopping:
    min_delta: 0.001
    mode: max
    monitor: recall@10
    patience: 100
  gpus: 1
  loggers:
    aim:
      experiment: ml-20m-extended-sasrec-100-plp-base-token-genres-nia
      repo: /home/ls6/fischer/model_logging/aim/
#    tensorboard:
#      name: ml-20m-extended-sasrec-100-plp-base-token-genres-nia
#      save_dir: /home/ls6/fischer/plp-paper/experiments/ml-20m-extended/sasrec/100-plp-base-token-genres-nia
  max_epochs: 100
