parser: &parser
  item_column_name: item_id
  item_separator: ' + '
loader: &loader
  batch_size: 3
  max_seq_length: 5
  max_seq_step_length: 5
datasets:
  test:
    dataset:
      csv_file: ../tests/example_dataset/train.csv
      csv_file_index: ../tests/example_dataset/train.idx
      nip_index_file: ../tests/example_dataset/train.nip.idx
      parser: *parser
    loader: *loader
  train:
    dataset:
      csv_file: ../tests/example_dataset/train.csv
      csv_file_index: ../tests/example_dataset/train.idx
      nip_index_file: ../tests/example_dataset/train.nip.idx
      parser: *parser
    loader: *loader
  validation:
    dataset:
      csv_file: ../tests/example_dataset/train.csv
      csv_file_index: ../tests/example_dataset/train.idx
      nip_index_file: ../tests/example_dataset/train.nip.idx
      parser: *parser
    loader: *loader
model:
  cell_type: gru
  item_vocab_size: 13
  item_embedding_dim: 4
  hidden_size: 4
  num_layers: 5
  dropout: 0.2
  embedding_pooling_type: mean
module:
  metrics:
    precision:
      - 1
      - 3
      - 5
    recall:
      - 1
      - 3
      - 5
    f1:
      - 1
      - 3
      - 5
tokenizer:
  special_tokens:
    pad_token: <PAD>
    mask_token: <MASK>
    unk_token: <UNK>
  vocabulary:
    delimiter: "\t"
    file: ../tests/example_dataset/vocab.txt
trainer:
  checkpoint:
    monitor: recall@5
    save_top_k: 3
