tokenizer:
  vocabulary:
    delimiter: "\t"
    file: "/home/dallmann/uni/research/dota/datasets/small/splits/items.vocab"
  special_tokens:
    pad_token: "<PAD>"
model:
  transformer_hidden_size: 16
  num_transformer_heads: 1
  num_transformer_layers: 1
  item_vocab_size: 248
  max_seq_length: 2047
  dropout: 0.1
module:
  batch_size: 4
  learning_rate: 0.001
  beta_1: 0.99
  beta_2: 0.998
  batch_first: true
  metrics_k:
    - 1
    - 3
    - 5
    - 10
datasets:
  train:
    dataset:
      csv_file: "/home/dallmann/uni/research/dota/datasets/small/splits/train.csv"
      csv_file_index: "/home/dallmann/uni/research/dota/datasets/small/splits/train.idx"
      delimiter: "\t"
      item_column_name: "item_id"
    loader:
      batch_size: 16
      max_seq_length: 2047
  validation:
    dataset:
      csv_file: "/home/dallmann/uni/research/dota/datasets/small/splits/valid.csv"
      csv_file_index: "/home/dallmann/uni/research/dota/datasets/small/splits/valid.idx"
      nip_index_file: "/home/dallmann/uni/research/dota/datasets/small/splits/valid.nip.idx"
      delimiter: "\t"
      item_column_name: "item_id"
    loader:
      batch_size: 16
      max_seq_length: 2047
  test:
    dataset:
      csv_file: "/home/dallmann/uni/research/dota/datasets/small/splits/test.csv"
      csv_file_index: "/home/dallmann/uni/research/dota/datasets/small/splits/test.idx"
      nip_index_file: "/home/dallmann/uni/research/dota/datasets/small/splits/test.nip.idx"
      delimiter: "\t"
      item_column_name: "item_id"
    loader:
      batch_size: 16
      max_seq_length: 2047
trainer:
  limit_train_batches: 10
  limit_val_batches: 10
  default_root_dir: /tmp/checkpoints
  checkpoint:
    save_top_k: 3
    monitor: "recall_at_5"




